name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Nim ${{ matrix.nim }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        nim: [1.6.x, 2.0.x, 2.2.4, 2.2.x, devel]
        exclude:
          - os: windows-latest
            nim: devel
    steps:
    - uses: actions/checkout@v7
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim }}
        use-nightlies: true
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-node@v7
      with:
        node-version: 24
        token: ${{ secrets.GITHUB_TOKEN }}
        package-manager-cache: false
    - name: Setup
      run: |
        nimble install -y --depsOnly
    - name: Run Tests
      run: |
        nimble test
    - name: Build docs
      if: matrix.nim == '1.6.x' && matrix.os == 'ubuntu-latest'
      run: |
        nimble docs
    - name: Deploy docs
      # to view docs on your own fork: push a gh-pages branch on your fork,
      # enable gh-pages in your fork
      # and remove `github.ref == 'refs/heads/master'` below
      if: |
        github.event_name == 'push' && github.ref == 'refs/heads/master' &&
        matrix.nim == '1.6.x' && matrix.os == 'ubuntu-latest'
      uses: crazy-max/ghaction-github-pages@v1
      with:
        build_dir: docs
        target_branch: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
